version: "3.3"
services:
  welfare_app:
    image: welfare_board_backend
    container_name: welfare_board_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./uploads:/usr/src/app/backend/uploads 

    ports:
      - "8070:3001"
    env_file:
      - .env
    networks:
      - backend_welfare-board-strapi


networks:
  backend_welfare-board-strapi:
    external: true